# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logger_pb2 as logger__pb2


class LoggerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateLog = channel.unary_unary(
                '/logger.LoggerService/CreateLog',
                request_serializer=logger__pb2.CreateRequest.SerializeToString,
                response_deserializer=logger__pb2.CreateResponse.FromString,
                )
        self.ReadLog = channel.unary_unary(
                '/logger.LoggerService/ReadLog',
                request_serializer=logger__pb2.ReadRequest.SerializeToString,
                response_deserializer=logger__pb2.ReadResponse.FromString,
                )
        self.ReadLogById = channel.unary_unary(
                '/logger.LoggerService/ReadLogById',
                request_serializer=logger__pb2.ReadRequestById.SerializeToString,
                response_deserializer=logger__pb2.ReadResponseById.FromString,
                )


class LoggerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLogById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateLog': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLog,
                    request_deserializer=logger__pb2.CreateRequest.FromString,
                    response_serializer=logger__pb2.CreateResponse.SerializeToString,
            ),
            'ReadLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLog,
                    request_deserializer=logger__pb2.ReadRequest.FromString,
                    response_serializer=logger__pb2.ReadResponse.SerializeToString,
            ),
            'ReadLogById': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLogById,
                    request_deserializer=logger__pb2.ReadRequestById.FromString,
                    response_serializer=logger__pb2.ReadResponseById.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logger.LoggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoggerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/CreateLog',
            logger__pb2.CreateRequest.SerializeToString,
            logger__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/ReadLog',
            logger__pb2.ReadRequest.SerializeToString,
            logger__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadLogById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/logger.LoggerService/ReadLogById',
            logger__pb2.ReadRequestById.SerializeToString,
            logger__pb2.ReadResponseById.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
