# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x06logger\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n\x0bVariantData\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\"\n\x08severity\x18\x02 \x01(\x0e\x32\x10.logger.Severity\x12\r\n\x05trace\x18\x03 \x01(\t\"O\n\rInvariantData\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\"\n\x08severity\x18\x02 \x01(\x0e\x32\x10.logger.Severity\x12\r\n\x05trace\x18\x03 \x01(\t\"\xcb\x01\n\x06Logger\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bsrc_service\x18\x04 \x01(\t\x12-\n\x0einvariant_data\x18\x05 \x01(\x0b\x32\x15.logger.InvariantData\x12)\n\x0cvariant_data\x18\x06 \x01(\x0b\x32\x13.logger.VariantData\"/\n\rCreateRequest\x12\x1e\n\x06logger\x18\x01 \x01(\x0b\x32\x0e.logger.Logger\"-\n\x0e\x43reateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x04\"\r\n\x0bReadRequest\".\n\x0cReadResponse\x12\x1e\n\x06logger\x18\x01 \x03(\x0b\x32\x0e.logger.Logger\"\"\n\x0fReadRequestById\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\"2\n\x10ReadResponseById\x12\x1e\n\x06logger\x18\x01 \x03(\x0b\x32\x0e.logger.Logger*7\n\x08Severity\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\t\n\x05\x46\x41TAL\x10\x03\x32\xc9\x01\n\rLoggerService\x12<\n\tCreateLog\x12\x15.logger.CreateRequest\x1a\x16.logger.CreateResponse\"\x00\x12\x36\n\x07ReadLog\x12\x13.logger.ReadRequest\x1a\x14.logger.ReadResponse\"\x00\x12\x42\n\x0bReadLogById\x12\x17.logger.ReadRequestById\x1a\x18.logger.ReadResponseById\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEVERITY._serialized_start=670
  _SEVERITY._serialized_end=725
  _VARIANTDATA._serialized_start=57
  _VARIANTDATA._serialized_end=134
  _INVARIANTDATA._serialized_start=136
  _INVARIANTDATA._serialized_end=215
  _LOGGER._serialized_start=218
  _LOGGER._serialized_end=421
  _CREATEREQUEST._serialized_start=423
  _CREATEREQUEST._serialized_end=470
  _CREATERESPONSE._serialized_start=472
  _CREATERESPONSE._serialized_end=517
  _READREQUEST._serialized_start=519
  _READREQUEST._serialized_end=532
  _READRESPONSE._serialized_start=534
  _READRESPONSE._serialized_end=580
  _READREQUESTBYID._serialized_start=582
  _READREQUESTBYID._serialized_end=616
  _READRESPONSEBYID._serialized_start=618
  _READRESPONSEBYID._serialized_end=668
  _LOGGERSERVICE._serialized_start=728
  _LOGGERSERVICE._serialized_end=929
# @@protoc_insertion_point(module_scope)
